version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
    time: "02:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: /cmd/pdc
  schedule:
    interval: daily
    time: "02:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
